### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by SirYaro**
add LINESP explanation

### CODE REVIEW

**Comment by berteh** [comment]
Thanks for the PR, but I don't quite get your explanation. Could you please elaborate ?

Just tested with Scribus 1.5.6.1 and the LINESP attribute is updated just fine by ScribusGenerator with most any usual XPath predicate, including //para, //para[last()] or others, as in the attached example files.

image

[spacing.csv.txt](https://github.com/berteh/ScribusGenerator/files/6321777/spacing.csv.txt)
[spacing.sla.txt](https://github.com/berteh/ScribusGenerator/files/6321778/spacing.sla.txt)

**Comment by berteh** [comment]
and yes, //trail does work too, and is useful. If you want to update the documentation again to add your "//trail" example please do, but not stating other XPath predicates don't work.

**Comment by SirYaro** [comment]
Hi Berteh.
It's very possible that I'm doing something wrong but no idea what would that be.

[tow_zw_test.sla.txt](https://github.com/berteh/ScribusGenerator/files/6327770/tow_zw_test.sla.txt)
[tow_zw_test.csv.txt](https://github.com/berteh/ScribusGenerator/files/6327771/tow_zw_test.csv.txt)

Attached sla have 3 LINESP attributes attached to "Tekst3" text box (the one with "%VAR_text%"). Out of this three only "trail" produce pdf with different line spacing. Others have no impact on text field whatsoever. Of course, normally I use only one of them at the time.

Would you mind taking a look ?

**Comment by berteh** [comment]
Just  checked, it works, nothing wrong with your template or the feature.

I remove all attributes for linesp but the first (//para), and added some paragraph (double linefeed) in the source CSV... otherwise there's nothing to see: [tow_zw_test2.csv.txt](https://github.com/berteh/ScribusGenerator/files/6396853/tow_zw_test2.csv.txt) - [tow_zw_test2.sla.txt](https://github.com/berteh/ScribusGenerator/files/6396854/tow_zw_test2.sla.txt)


image

**Pull request closed without merging**
